# Fichier de configuration pour Netlify

[build]
  # Indique à Netlify d'abord aller dans le dossier 'frontend'
  base    = "frontend"
  # La commande pour construire le site
  command = "npm run build"
  # Le site final à publier se trouvera dans le dossier frontend/dist
  publish = "frontend/dist"

# Notre règle de redirection pour les applications React
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200